#!/bin/sh
# POSIX compliant script to search browser
set -e # stop at first error
#set -x # debug 

BDOCUMENTSTEM="/usr/share/scp-foundation-doc-cn/html/scp-wiki-cn.wikidot.com"
if [ -r "${BDOCUMENTSTEM}/index.html" ]; then
  /usr/bin/sensible-browser "${BDOCUMENTSTEM}/index.html"
fi
